-- ============================================================
-- supabase/seed.sql
-- Production seed — minimal data, ready for scraper pipeline.
--
-- Data flow:
-- 1. Migrations 00001–00012 create schema + functions
-- 2. This seed (empty state for production)
-- 3. Python scraper imports AmazonCategories.csv:
--    POST http://scraper/categories/import { csv_path: "..." }
--    → calls upsert_category() for 25k+ rows
-- 4. Embedding generation (after CSV):
--    POST http://scraper/categories/embed
--    → generates embeddings for all categories via OpenAI
-- 5. Product scraping + global catalog population (continuous background job)
-- 6. Supplier matching pipeline (async, triggered after each product upsert)
-- ============================================================

-- Schema is ready. No test data to prevent production pollution.
-- All tables are initialized and ready for data flow from scraper pipelines.

-- Reference: Available functions for scraper integration
-- ────────────────────────────────────────────────────
-- Categories:
--   SELECT upsert_category(id, name, parent_id, full_path, breadcrumb, depth, is_leaf, marketplace)
--   SELECT search_categories(query, marketplace, limit)
--   SELECT match_categories_semantic(embedding, marketplace, count, min_similarity)
-- 
-- Products:
--   INSERT INTO products (...) ON CONFLICT (asin, marketplace) DO UPDATE ...
--   SELECT claim_products_for_refresh(batch_size)  -- SKIP LOCKED batch queue
-- 
-- Usage Counters (plan enforcement):
--   SELECT increment_usage_counter(user_id, key, period)  -- returns new count
--   SELECT get_usage_count(user_id, key, period)
-- 
-- Suppliers (async matching):
--   POST scraper /categories/embed
--   POST scraper /suppliers/match { product_batch }
--   → upserts into product_embeddings, supplier_embeddings, product_supplier_matches
-- 
-- See docs/DATABASE.md for full schema reference.
-- See docs/EMBEDDING_STRATEGY.md for embedding pipeline details.
