/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerIndexRouteImport } from './routes/tracker/index'
import { Route as SourcingIndexRouteImport } from './routes/sourcing/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as CostCalculatorIndexRouteImport } from './routes/cost-calculator/index'
import { Route as CompetitorIntelIndexRouteImport } from './routes/competitor-intel/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BrandbookIndexRouteImport } from './routes/brandbook/index'
import { Route as AnalyzerIndexRouteImport } from './routes/analyzer/index'
import { Route as CompetitorIntelAsinRouteImport } from './routes/competitor-intel/$asin'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AnalyzerAsinRouteImport } from './routes/analyzer/$asin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingIndexRoute = SourcingIndexRouteImport.update({
  id: '/sourcing/',
  path: '/sourcing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCalculatorIndexRoute = CostCalculatorIndexRouteImport.update({
  id: '/cost-calculator/',
  path: '/cost-calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorIntelIndexRoute = CompetitorIntelIndexRouteImport.update({
  id: '/competitor-intel/',
  path: '/competitor-intel/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandbookIndexRoute = BrandbookIndexRouteImport.update({
  id: '/brandbook/',
  path: '/brandbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerIndexRoute = AnalyzerIndexRouteImport.update({
  id: '/analyzer/',
  path: '/analyzer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorIntelAsinRoute = CompetitorIntelAsinRouteImport.update({
  id: '/competitor-intel/$asin',
  path: '/competitor-intel/$asin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerAsinRoute = AnalyzerAsinRouteImport.update({
  id: '/analyzer/$asin',
  path: '/analyzer/$asin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer/$asin': typeof AnalyzerAsinRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/competitor-intel/$asin': typeof CompetitorIntelAsinRoute
  '/analyzer/': typeof AnalyzerIndexRoute
  '/brandbook/': typeof BrandbookIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitor-intel/': typeof CompetitorIntelIndexRoute
  '/cost-calculator/': typeof CostCalculatorIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sourcing/': typeof SourcingIndexRoute
  '/tracker/': typeof TrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer/$asin': typeof AnalyzerAsinRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/competitor-intel/$asin': typeof CompetitorIntelAsinRoute
  '/analyzer': typeof AnalyzerIndexRoute
  '/brandbook': typeof BrandbookIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/competitor-intel': typeof CompetitorIntelIndexRoute
  '/cost-calculator': typeof CostCalculatorIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sourcing': typeof SourcingIndexRoute
  '/tracker': typeof TrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer/$asin': typeof AnalyzerAsinRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/competitor-intel/$asin': typeof CompetitorIntelAsinRoute
  '/analyzer/': typeof AnalyzerIndexRoute
  '/brandbook/': typeof BrandbookIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitor-intel/': typeof CompetitorIntelIndexRoute
  '/cost-calculator/': typeof CostCalculatorIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sourcing/': typeof SourcingIndexRoute
  '/tracker/': typeof TrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer/$asin'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/competitor-intel/$asin'
    | '/analyzer/'
    | '/brandbook/'
    | '/categories/'
    | '/competitor-intel/'
    | '/cost-calculator/'
    | '/discover/'
    | '/notifications/'
    | '/research/'
    | '/settings/'
    | '/sourcing/'
    | '/tracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer/$asin'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/competitor-intel/$asin'
    | '/analyzer'
    | '/brandbook'
    | '/categories'
    | '/competitor-intel'
    | '/cost-calculator'
    | '/discover'
    | '/notifications'
    | '/research'
    | '/settings'
    | '/sourcing'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/analyzer/$asin'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/competitor-intel/$asin'
    | '/analyzer/'
    | '/brandbook/'
    | '/categories/'
    | '/competitor-intel/'
    | '/cost-calculator/'
    | '/discover/'
    | '/notifications/'
    | '/research/'
    | '/settings/'
    | '/sourcing/'
    | '/tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerAsinRoute: typeof AnalyzerAsinRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CompetitorIntelAsinRoute: typeof CompetitorIntelAsinRoute
  AnalyzerIndexRoute: typeof AnalyzerIndexRoute
  BrandbookIndexRoute: typeof BrandbookIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CompetitorIntelIndexRoute: typeof CompetitorIntelIndexRoute
  CostCalculatorIndexRoute: typeof CostCalculatorIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SourcingIndexRoute: typeof SourcingIndexRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/tracker'
      fullPath: '/tracker/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/': {
      id: '/sourcing/'
      path: '/sourcing'
      fullPath: '/sourcing/'
      preLoaderRoute: typeof SourcingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-calculator/': {
      id: '/cost-calculator/'
      path: '/cost-calculator'
      fullPath: '/cost-calculator/'
      preLoaderRoute: typeof CostCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitor-intel/': {
      id: '/competitor-intel/'
      path: '/competitor-intel'
      fullPath: '/competitor-intel/'
      preLoaderRoute: typeof CompetitorIntelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandbook/': {
      id: '/brandbook/'
      path: '/brandbook'
      fullPath: '/brandbook/'
      preLoaderRoute: typeof BrandbookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer/': {
      id: '/analyzer/'
      path: '/analyzer'
      fullPath: '/analyzer/'
      preLoaderRoute: typeof AnalyzerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitor-intel/$asin': {
      id: '/competitor-intel/$asin'
      path: '/competitor-intel/$asin'
      fullPath: '/competitor-intel/$asin'
      preLoaderRoute: typeof CompetitorIntelAsinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer/$asin': {
      id: '/analyzer/$asin'
      path: '/analyzer/$asin'
      fullPath: '/analyzer/$asin'
      preLoaderRoute: typeof AnalyzerAsinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerAsinRoute: AnalyzerAsinRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CompetitorIntelAsinRoute: CompetitorIntelAsinRoute,
  AnalyzerIndexRoute: AnalyzerIndexRoute,
  BrandbookIndexRoute: BrandbookIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CompetitorIntelIndexRoute: CompetitorIntelIndexRoute,
  CostCalculatorIndexRoute: CostCalculatorIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SourcingIndexRoute: SourcingIndexRoute,
  TrackerIndexRoute: TrackerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
