#!/usr/bin/env node
// scripts/env-sync.js
//
// Reads the root .env (source of truth) and distributes it to each app.
// Usage: npm run env:sync
//
// Each app gets its own copy so native tooling (Next.js, dotenv, IDEs) picks
// it up automatically without any custom loading logic.

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')

const SOURCE = path.join(ROOT, '.env')

// Each app and the filename it expects
const TARGETS = [
    { app: 'apps/web', file: '.env.local' },
    { app: 'apps/scraper', file: '.env' },
]

// ── Parse root .env ───────────────────────────────────────────────────────────

if (!fs.existsSync(SOURCE)) {
    console.error('❌  Root .env not found. Copy .env.example → .env and fill in values.')
    process.exit(1)
}

const raw = fs.readFileSync(SOURCE, 'utf8')

// Keep only non-comment, non-blank lines for the generated files (clean output)
const varLines = raw
    .split('\n')
    .filter(line => line.trim() && !line.trim().startsWith('#'))

const generated = [
    '# ⚠️  Generated by `npm run env:sync` — do not edit manually.',
    '# Edit the root .env file and re-run the command.',
    '',
    ...varLines,
    '',
].join('\n')

// ── Write to each target ──────────────────────────────────────────────────────

for (const { app, file } of TARGETS) {
    const dest = path.join(ROOT, app, file)
    fs.writeFileSync(dest, generated, 'utf8')
    console.log(`✔  Written → ${app}/${file}`)
}

console.log('\n✅  All apps are in sync with root .env')
