#!/usr/bin/env node
// scripts/env-sync.js
//
// Reads the root .env (source of truth) and distributes it to each app.
// Generic key names are transformed to the prefix each build tool requires:
//   apps/web        → NEXT_PUBLIC_ prefix for browser-exposed vars
//   apps/extension  → VITE_ prefix for browser-exposed vars
//   apps/scraper    → no prefix (Node.js process.env)
//
// Usage: npm run env:sync
//   Add the root .env to .gitignore — it holds real secrets.
//   Never commit per-app .env.local files either.

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SOURCE = path.join(ROOT, '.env')

// ── Which generic keys get exposed in the browser ─────────────────────────────
// All other keys are either server-only or completely excluded from that app.
const BROWSER_PUBLIC_KEYS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY']

// DATABASE_URL is server-only (never exposed to browser / extension)
// It points to Fly.io Postgres and is used by apps/web and apps/scraper only.
// DATABASE_PROXY_URL is an optional local-dev override for a Fly proxy tunnel.
// Vector variables are also server-only. They are passed through unchanged to
// apps/web and apps/scraper so laptop/mac-mini setups can share one root .env.

// ── Target definitions ────────────────────────────────────────────────────────
const TARGETS = [
    {
        app: 'apps/web',
        file: '.env.local',
        // `true` = expose to browser with NEXT_PUBLIC_ prefix
        renames: Object.fromEntries(BROWSER_PUBLIC_KEYS.map((k) => [k, `NEXT_PUBLIC_${k}`])),
        // Keys that the web app doesn't need at all
        exclude: [
            'WEB_APP_ORIGIN',
            'SUPABASE_PASSWORD',
            'VECTOR_SYNC_BATCH_SIZE',
            'VECTOR_SYNC_POLL_MS',
            'VECTOR_SYNC_STATE_FILE',
            'VECTOR_OPENAI_BATCH_SIZE',
            'VECTOR_OPENAI_BATCH_POLL_MS',
            'VECTOR_OPENAI_BATCH_STATE_FILE',
        ],
        // DATABASE_URL / DATABASE_PROXY_URL pass through as-is (server-only, used by integrations/flyio/client.ts)
    },
    {
        app: 'apps/scraper',
        file: '.env',
        renames: {},
        // Variables that are only needed browser-side or extension-side
        // DATABASE_URL / DATABASE_PROXY_URL pass through as-is (used by shared/db.ts → @puckora/db createDb)
        exclude: ['WEB_APP_ORIGIN'],
    },
    {
        app: 'apps/extension',
        file: '.env.local',
        // Extension bundled by Vite — all runtime vars need VITE_ prefix
        renames: Object.fromEntries(
            [...BROWSER_PUBLIC_KEYS, 'WEB_APP_ORIGIN'].map((k) => [k, `VITE_${k}`])
        ),
        // Server-only secrets must never be bundled into the extension
        // DATABASE_URL and DATABASE_PROXY_URL are excluded — extension never connects to Postgres directly
        exclude: [
            'DATABASE_URL',
            'DATABASE_PROXY_URL',
            'VECTOR_DATABASE_URL',
            'VECTOR_EMBEDDING_PROVIDER',
            'VECTOR_EMBEDDING_MODEL',
            'VECTOR_EMBEDDING_DIMENSIONS',
            'VECTOR_OLLAMA_BASE_URL',
            'VECTOR_SYNC_BATCH_SIZE',
            'VECTOR_SYNC_POLL_MS',
            'VECTOR_SYNC_STATE_FILE',
            'VECTOR_OPENAI_BATCH_SIZE',
            'VECTOR_OPENAI_BATCH_POLL_MS',
            'VECTOR_OPENAI_BATCH_STATE_FILE',
            'VECTOR_MIN_SCORE',
            'VECTOR_QUERY_LIMIT',
            'SUPABASE_SERVICE_ROLE_KEY',
            'SUPABASE_PASSWORD',
            'SP_CLIENT_ID',
            'SP_CLIENT_SECRET',
            'SP_REFRESH_TOKEN',
            'SP_MARKETPLACE_ID',
            'APIFY_API_TOKEN',
            'OPENAI_API_KEY',
            'OPENAI_EMBEDDING_MODEL',
            'STRIPE_SECRET_KEY',
            'STRIPE_WEBHOOK_SECRET',
            'PROXY_URL',
        ],
    },
]

// ── Parse root .env ───────────────────────────────────────────────────────────

if (!fs.existsSync(SOURCE)) {
    console.error('❌  Root .env not found. Copy .env.example → .env and fill in values.')
    process.exit(1)
}

const raw = fs.readFileSync(SOURCE, 'utf8')

// Parse into { key: rawLine } preserving inline comments and quotes
const entries = []
for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = line.indexOf('=')
    if (eqIdx === -1) continue
    const key = line.slice(0, eqIdx).trim()
    const rest = line.slice(eqIdx + 1) // value + optional inline comment
    entries.push({ key, rest })
}

// ── Write to each target ──────────────────────────────────────────────────────

for (const { app, file, renames, exclude } of TARGETS) {
    const lines = [
        '# ⚠️  Generated by `npm run env:sync` — do not edit manually.',
        '# Edit the root .env file and re-run the command.',
        '',
    ]

    for (const { key, rest } of entries) {
        if (exclude.includes(key)) continue
        const outputKey = renames[key] ?? key
        lines.push(`${outputKey}=${rest}`)
    }

    lines.push('')
    const dest = path.join(ROOT, app, file)
    fs.writeFileSync(dest, lines.join('\n'), 'utf8')
    console.log(`✔  Written → ${app}/${file}`)
}

console.log('\n✅  All apps are in sync with root .env')
