/**
 * i18n-generate-types.ts
 *
 * Regenerates `apps/web/src/locales/i18n.d.ts` from the actual locale files
 * found under `apps/web/src/locales/en/`.
 *
 * Run:  npm run i18n:types
 *
 * When to run:
 *  - After adding a new namespace file (e.g. en/onboarding.json)
 *  - After renaming a namespace file
 *  - As part of CI to ensure types stay in sync
 */

import { readdirSync, writeFileSync, existsSync } from 'fs'
import { resolve, basename } from 'path'

const LOCALES_DIR = resolve(__dirname, '../apps/web/src/locales')
const EN_DIR = resolve(LOCALES_DIR, 'en')
const OUTPUT_FILE = resolve(LOCALES_DIR, 'i18n.d.ts')

function getNamespaces(): string[] {
    if (!existsSync(EN_DIR)) {
        console.error(`❌  en/ directory not found at ${EN_DIR}`)
        process.exit(1)
    }
    return readdirSync(EN_DIR)
        .filter((f) => f.endsWith('.json'))
        .map((f) => basename(f, '.json'))
        .sort()
}

function generateImports(namespaces: string[]): string {
    return namespaces
        .map((ns) => `import type ${ns} from './en/${ns}.json'`)
        .join('\n')
}

function generateResources(namespaces: string[]): string {
    return namespaces.map((ns) => `            ${ns}: typeof ${ns}`).join('\n')
}

function generateFile(namespaces: string[]): string {
    const defaultNS = namespaces.includes('common') ? 'common' : namespaces[0]

    return `/**
 * i18n type augmentation for i18next.
 * This file is AUTO-GENERATED by \`npm run i18n:types\`.
 * Do not edit manually — run the script after adding/renaming locale files.
 *
 * All \`useTranslation(ns)\` calls and \`t()\` calls are fully type-checked against
 * the actual locale JSON files in \`src/locales/en/\`.
 */

${generateImports(namespaces)}

declare module 'i18next' {
    interface CustomTypeOptions {
        /** Default namespace used when no \`ns\` is passed to \`useTranslation()\` */
        defaultNS: '${defaultNS}'
        /** Enables TypeScript errors for missing/extra translation keys */
        resources: {
${generateResources(namespaces)}
        }
    }
}
`
}

function generateConfig(namespaces: string[]): string {
    const nsLiteral = namespaces.map((n) => `    '${n}',`).join('\n')
    return `/**
 * Master list of i18n namespaces.
 * This is the single source of truth — add new namespaces here and re-run
 * \`npm run i18n:types\` to regenerate type augmentation.
 *
 * AUTO-GENERATED by \`npm run i18n:types\`. Do not edit manually.
 */
export const NAMESPACES = [
${nsLiteral}
] as const

export type Namespace = (typeof NAMESPACES)[number]

export const SUPPORTED_LANGUAGES = ['en', 'es'] as const

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number]

export const LANGUAGE_LABELS: Record<SupportedLanguage, string> = {
    en: 'English',
    es: 'Español',
}

export const DEFAULT_LANGUAGE: SupportedLanguage = 'en'
export const DEFAULT_NAMESPACE: Namespace = '${namespaces.includes('common') ? 'common' : namespaces[0]}'
`
}

const namespaces = getNamespaces()

writeFileSync(OUTPUT_FILE, generateFile(namespaces), 'utf-8')
console.log(`✅  Generated ${OUTPUT_FILE}`)
console.log(`   Namespaces: ${namespaces.join(', ')}`)

// Also regenerate config.ts so NAMESPACES array stays in sync
const configFile = resolve(LOCALES_DIR, 'config.ts')
writeFileSync(configFile, generateConfig(namespaces), 'utf-8')
console.log(`✅  Updated   ${configFile}`)
