/**
 * Master list of i18n namespaces.
 * This is the single source of truth — add new namespaces here and re-run
 * `npm run i18n:types` to regenerate type augmentation.
 *
 * AUTO-GENERATED by `npm run i18n:types`. Do not edit manually.
 */
export const NAMESPACES = [
    'analyzer',
    'auth',
    'calculator',
    'categories',
    'common',
    'competitor',
    'discover',
    'nav',
    'onboarding',
    'plans',
    'research',
    'settings',
    'sourcing',
    'tracker',
] as const

export type Namespace = (typeof NAMESPACES)[number]

export const SUPPORTED_LANGUAGES = ['en', 'es'] as const

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number]

export const LANGUAGE_LABELS: Record<SupportedLanguage, string> = {
    en: 'English',
    es: 'Español',
}

export const DEFAULT_LANGUAGE: SupportedLanguage = 'en'
export const DEFAULT_NAMESPACE: Namespace = 'common'
