/**
 * i18n type augmentation for i18next.
 * This file is AUTO-GENERATED by `npm run i18n:types`.
 * Do not edit manually — run the script after adding/renaming locale files.
 *
 * All `useTranslation(ns)` calls and `t()` calls are fully type-checked against
 * the actual locale JSON files in `src/locales/en/`.
 */

import type analyzer from './en/analyzer.json'
import type auth from './en/auth.json'
import type calculator from './en/calculator.json'
import type categories from './en/categories.json'
import type common from './en/common.json'
import type competitor from './en/competitor.json'
import type discover from './en/discover.json'
import type nav from './en/nav.json'
import type onboarding from './en/onboarding.json'
import type plans from './en/plans.json'
import type research from './en/research.json'
import type settings from './en/settings.json'
import type sourcing from './en/sourcing.json'
import type tracker from './en/tracker.json'

declare module 'i18next' {
    interface CustomTypeOptions {
        /** Default namespace used when no `ns` is passed to `useTranslation()` */
        defaultNS: 'common'
        /** Enables TypeScript errors for missing/extra translation keys */
        resources: {
            analyzer: typeof analyzer
            auth: typeof auth
            calculator: typeof calculator
            categories: typeof categories
            common: typeof common
            competitor: typeof competitor
            discover: typeof discover
            nav: typeof nav
            onboarding: typeof onboarding
            plans: typeof plans
            research: typeof research
            settings: typeof settings
            sourcing: typeof sourcing
            tracker: typeof tracker
        }
    }
}
