-- ============================================================
-- 00007_analysis_opportunities.sql
-- Competitor analysis jobs, pain-point NLP clusters,
-- opportunity reports, and the global market opportunity board.
-- ============================================================

-- ── Competitor analysis jobs ──────────────────────────────────
CREATE TABLE IF NOT EXISTS competitor_analyses (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id) ON DELETE SET NULL,  -- linked global product

  -- Request parameters
  asin         TEXT NOT NULL,
  marketplace  marketplace NOT NULL DEFAULT 'US',
  max_reviews  INT NOT NULL DEFAULT 200,
  min_rating   INT CHECK (min_rating BETWEEN 1 AND 5),
  max_rating   INT CHECK (max_rating BETWEEN 1 AND 5),

  -- Job state machine
  status       job_status NOT NULL DEFAULT 'pending',
  error_message TEXT,

  -- Progress tracking
  reviews_scraped INT NOT NULL DEFAULT 0,
  reviews_clustered INT NOT NULL DEFAULT 0,

  -- Timing
  queued_at    TIMESTAMPTZ,
  started_at   TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_competitor_analyses_updated_at
  BEFORE UPDATE ON competitor_analyses
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX IF NOT EXISTS idx_competitor_analyses_user
  ON competitor_analyses(user_id);

CREATE INDEX IF NOT EXISTS idx_competitor_analyses_status
  ON competitor_analyses(status)
  WHERE status IN ('pending', 'queued', 'processing');

CREATE INDEX IF NOT EXISTS idx_competitor_analyses_product
  ON competitor_analyses(product_id)
  WHERE product_id IS NOT NULL;

-- ── Pain point NLP clusters ───────────────────────────────────
-- Each row is one thematic cluster identified from negative reviews.
CREATE TABLE IF NOT EXISTS pain_point_clusters (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  analysis_id     UUID NOT NULL REFERENCES competitor_analyses(id) ON DELETE CASCADE,

  cluster_label   TEXT NOT NULL,   -- short label: 'Battery life'
  cluster_theme   TEXT NOT NULL,   -- longer theme: 'Product stops working after short use'
  mention_count   INT NOT NULL DEFAULT 0,
  severity_score  NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (severity_score BETWEEN 0 AND 100),
  is_actionable   BOOLEAN NOT NULL DEFAULT FALSE,  -- can a product improvement address this?
  opportunity_signal TEXT,  -- free-text: 'Add a larger battery or USB-C charging'
  representative_quotes TEXT[] DEFAULT '{}',
  avg_rating_in_cluster NUMERIC(3,2),

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pain_clusters_analysis
  ON pain_point_clusters(analysis_id);

-- ── Opportunity reports (one per completed analysis) ─────────
CREATE TABLE IF NOT EXISTS opportunity_reports (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  analysis_id     UUID NOT NULL UNIQUE REFERENCES competitor_analyses(id) ON DELETE CASCADE,

  -- Summary
  market_gap_summary     TEXT,
  suggested_improvements TEXT[] DEFAULT '{}',
  dissatisfaction_rate   NUMERIC(5,2),  -- % negative reviews in sample
  opportunity_score      NUMERIC(5,2) CHECK (opportunity_score BETWEEN 0 AND 100),

  -- Structured top opportunities (denormalised for quick display)
  top_opportunities JSONB NOT NULL DEFAULT '[]',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Global market opportunity board ──────────────────────────
-- Market-level signals generated by batch analytics jobs.
-- Not per-user — shown in the "Opportunities" module to everyone.
-- The Python backend writes here after aggregating across ASINs.
CREATE TABLE IF NOT EXISTS market_opportunities (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Scope
  category_id  TEXT REFERENCES amazon_categories(id) ON DELETE SET NULL,
  marketplace  marketplace NOT NULL DEFAULT 'US',
  signal_type  opportunity_type NOT NULL,

  -- Content
  title        TEXT NOT NULL,
  description  TEXT,
  score        NUMERIC(5,2) CHECK (score BETWEEN 0 AND 100),
  data         JSONB,  -- { asin_examples: [], avg_bsr: 12000, ... }

  -- Related products
  example_asins TEXT[] DEFAULT '{}',

  -- Lifecycle: opportunities expire and are refreshed by cron
  valid_until  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_market_opportunities_updated_at
  BEFORE UPDATE ON market_opportunities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX IF NOT EXISTS idx_market_opps_category
  ON market_opportunities(category_id, marketplace, score DESC);

CREATE INDEX IF NOT EXISTS idx_market_opps_active
  ON market_opportunities(valid_until);

CREATE INDEX IF NOT EXISTS idx_market_opps_type
  ON market_opportunities(signal_type, marketplace);

-- ── Trend signals (BSR momentum, review velocity) ────────────
-- Computed daily by the background job from product_history.
-- Surfaced in the "Trending" section.
CREATE TABLE IF NOT EXISTS trend_signals (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id  UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  marketplace marketplace NOT NULL DEFAULT 'US',

  signal_type TEXT NOT NULL,  -- 'bsr_rising', 'bsr_falling', 'review_velocity_spike'
  value       NUMERIC(12,4),  -- e.g. % change
  period_days INT NOT NULL DEFAULT 30,  -- lookback window

  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),

  UNIQUE(product_id, signal_type, period_days)
);

CREATE INDEX IF NOT EXISTS idx_trend_signals_product
  ON trend_signals(product_id);

CREATE INDEX IF NOT EXISTS idx_trend_signals_active
  ON trend_signals(marketplace, signal_type, value DESC);
